### ISSUE TITLE
Person Mentions - some Cosmetics, a small Addition

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/fa-data#24]
The INT16_Segment has the triple
```
ns1:R41_has_location "72"^^xsd:string ;
```

- [x]  Please add "S. " before the number.

- [x]  Also, add another object to the triple: the permalink to the Fackel online, in this case e.g. (depending on the issue, of course): 
```
"https://fackel.oeaw.ac.at/f/781,072"^^xsd:string ;"
```
Final version of the triple:
```
ns1:R41_has_location "S. 72"^^xsd:string, "https://fackel.oeaw.ac.at/f/781,072"^^xsd:string ;
```
Thanks!

**Comment by BergListe** [comment]
Done. Added a template to generate a valid fackel-link from any given fackel file name.

Having problems to run the transformation due to lack of RAM on my office computer.

Results will be pushed to: https://gitlab.oeaw.ac.at/acdh-ch/ace/semanticKraus/fackel-export/-/blob/main/rdf/fackel_mentions.ttl?ref_type=heads

**Comment by BOberreither** [comment]
@BergListe Works mostly; one data error in drive fackellist is already fixed, so the next version should automatically contain less bugs; one thing: Depending on the result in the next version, we might need a filter to ignore mentions that are outside of our text boundaries (and in, e.g., adverts or on cover pages).

**Comment by BOberreither** [comment]
@BOberreither ("n_143" shouldn't exist then, for example.)
